# Generated by Django 4.1.7 on 2023-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by_staff",
            field=models.BooleanField(default=False),
        ),
    ]
