# Generated by Django 4.1.7 on 2023-03-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_created_by_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_profile", "Can view profile"),
                    ("change_profile", "Can update profile"),
                    ("reset_password", "Can reset password"),
                    ("add_user_to_group", "Can add user to group"),
                    ("add_permission_to_user", "Can add permission to user"),
                ]
            },
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
