# Generated by Django 4.1.7 on 2023-04-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_profile", "Can view profile"),
                    ("view_setting", "Can view setting"),
                    ("change_profile", "Can update profile"),
                    ("reset_password", "Can reset password"),
                    ("add_user_to_group", "Can add user to group"),
                    ("add_patient", "Can add patient"),
                    ("change_patient", "Can update patient"),
                    ("add_permission_to_user", "Can add permission to user"),
                ]
            },
        ),
    ]
