# Generated by Django 4.1.7 on 2023-03-23 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("blood_type", models.CharField(max_length=5)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=10)),
                ("medical_condition", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=10)),
                ("ocupation", models.CharField(max_length=100)),
                ("id_type", models.CharField(max_length=20)),
                ("id_number", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blood_type", models.CharField(max_length=5)),
                ("dob", models.DateField()),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=15)),
                ("gender", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donation_id",
                    models.CharField(default="generate_donation_id()", max_length=20),
                ),
                ("date_time_donated", models.DateTimeField()),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.donor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_request_id",
                    models.CharField(default="generate_request_id()", max_length=20),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=5)),
                ("status", models.CharField(max_length=20)),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                ("date_approve_rejected", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.patientprofile",
                    ),
                ),
            ],
        ),
    ]
