# Generated by Django 4.1.7 on 2023-03-23 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_patientprofile_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
