# Generated by Django 4.1.7 on 2023-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_donor_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="email",
            field=models.EmailField(default="default@gmail.com", max_length=254),
        ),
    ]
