# Generated by Django 4.1.7 on 2023-03-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_donor_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="blood_type",
            field=models.CharField(max_length=15),
        ),
    ]
