# Generated by Django 4.1.7 on 2023-04-23 18:33

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0006_alter_donor_blood_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_request_id",
            field=models.CharField(
                default=dashboard.models.BloodRequest.generate_request_id, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_id",
            field=models.CharField(
                default=dashboard.models.Donation.generate_donation_id, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.donor",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
