# Generated by Django 4.1.7 on 2023-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_bloodrequest_blood_request_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="date_time_donated",
            field=models.DateField(),
        ),
    ]
