# Generated by Django 4.1.7 on 2023-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_alter_donation_date_time_donated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="date_time_donated",
            field=models.DateTimeField(),
        ),
    ]
