# Generated by Django 4.1.7 on 2023-04-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_alter_bloodrequest_patient_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="request_form",
            field=models.ImageField(blank=True, null=True, upload_to="request_forms"),
        ),
    ]
