# Generated by Django 4.1.7 on 2023-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_bloodrequest_request_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(max_length=15),
        ),
    ]
